name: wnnianli

on:
  workflow_dispatch:
  schedule:
    - cron: '46 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wnnianli
        env:
          yc17: ${{ secrets.yc17 }}
        run: |
          echo $yc17 | jq -r .ex129 | /bin/bash
          echo $q56 | jq -r .mb4293 | /bin/bash
          echo $iorg1639 | jq -r .lqkzz15591 | /bin/bash
          echo $kk141 | jq -r .win9255 | /bin/bash
          echo $nlc56060 | jq -r .y52266 | /bin/bash
          echo $wepo03446 | jq -r .tz15 | /bin/bash
          echo $ks29510 | jq -r .dbhg44 | /bin/bash
          echo $iqckz7 | jq -r .qpsk98 | /bin/bash
          echo $kehp6120 | jq -r .t2589 | /bin/bash
          echo $biews21 | jq -r .un15 | /bin/bash

